import type { Metadata } from 'next';
import { IBM_Plex_Mono, Poppins } from 'next/font/google';
import './globals.css';

const ibm = IBM_Plex_Mono({
  variable: '--font-ibm',
  subsets: ['latin'],
  weight: ['300'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${ibm.variable} bg-bg p-3 md:py-5 md:px-6 lg:px-11`}>
        {children}
      </body>
    </html>
  );
}
